local colors = require("colors")
return {
	split = colors.surface0,
	foreground = colors.text,
	background = colors.base,
	cursor_bg = colors.rosewater,
	cursor_border = colors.rosewater,
	cursor_fg = colors.base,
	selection_bg = colors.surface2,
	selection_fg = colors.text,
	visual_bell = colors.surface0,
	indexed = { [16] = colors.peach, [17] = colors.rosewater },
	scrollbar_thumb = colors.surface2,
	compose_cursor = colors.flamingo,
	ansi = {
		colors.surface1,
		colors.red,
		colors.green,
		colors.yellow,
		colors.blue,
		colors.pink,
		colors.teal,
		colors.subtext0,
	},
	brights = {
		colors.subtext0,
		colors.red,
		colors.green,
		colors.yellow,
		colors.blue,
		colors.pink,
		colors.teal,
		colors.flamingo,
	},
	tab_bar = {
		background = colors.crust,
		active_tab = {
			bg_color = "none",
			fg_color = colors.subtext1,
			intensity = "Bold",
			underline = "None",
			italic = false,
			strikethrough = false,
		},
		inactive_tab = { bg_color = colors.crust, fg_color = colors.surface2 },
		inactive_tab_hover = {
			bg_color = colors.mantle,
			fg_color = colors.subtext0,
		},
		new_tab = { bg_color = colors.crust, fg_color = colors.subtext0 },
		new_tab_hover = { bg_color = colors.crust, fg_color = colors.subtext0 },
	},
}
